# Install the `agent-skills` command onto PATH on Windows.
#
#   powershell -ExecutionPolicy Bypass -File install.ps1
#   $env:BIN_DIR = "$HOME\bin"; powershell -ExecutionPolicy Bypass -File install.ps1
#
# The sh installer cannot be used here, for two reasons that have nothing to do
# with each other:
#
#   1. `ln -s` needs SeCreateSymbolicLinkPrivilege, which a normal user only has
#      with Developer Mode on (see #32)
#   2. cmd.exe and PowerShell do not read `#!/usr/bin/env node`, so even a
#      successful link would not be runnable
#
# So this writes .cmd shims instead of links. The repo path goes into a user
# environment variable rather than into the shims, because cmd.exe reads a .cmd
# in whatever codepage the console happens to be in: a path written as OEM 932
# is misread by a terminal sitting at 65001, and vice versa. One non-ASCII
# character in the path — a Japanese username is enough — and the shim silently
# points at nothing. Environment variables are stored as Unicode and expanded by
# cmd itself, so the shims stay pure ASCII and the encoding question disappears.
# (8.3 short paths do not save us: a short directory name like 戸倉健 gets no
# alias, so non-ASCII survives.)
#
# Moving the repo means re-running this script, which is what rewrites the
# variable.
#
# Idempotent.
$ErrorActionPreference = 'Stop'

$src = Join-Path $PSScriptRoot 'bin\agent-skills'
if (-not (Test-Path $src)) {
    Write-Error "install: $src not found - run from the repo root"
    exit 1
}
$src = (Resolve-Path $src).Path

$binDir = $env:BIN_DIR
if (-not $binDir) { $binDir = Join-Path $env:USERPROFILE '.local\bin' }

# Node version gate (same floor as scripts/run.js). Only ever a warning - the
# command itself re-checks and prints the full fix.
$node = Get-Command node -ErrorAction SilentlyContinue
if ($node) {
    $v = $null
    try { $v = (& node -p 'process.versions.node' 2>$null) } catch {}
    if ($v -match '^(\d+)\.(\d+)') {
        $major = [int]$Matches[1]
        $minor = [int]$Matches[2]
        if ($major -lt 22 -or ($major -eq 22 -and $minor -lt 18)) {
            Write-Warning "install: Node $v < 22.18; the command needs >= 22.18 to run."
        }
    } else {
        Write-Warning "install: node is on PATH but would not report a version. Needs Node >= 22.18."
    }
} else {
    Write-Warning "install: node not found on PATH; install Node >= 22.18."
}

if (-not (Test-Path $binDir)) { New-Item -ItemType Directory -Path $binDir -Force | Out-Null }

$repo = Split-Path $src -Parent | Split-Path -Parent

# The marker separates "we wrote this" from "something else owns this name".
# Without it a shim left over from an older version is indistinguishable from a
# stranger's file, and we would refuse to fix the very case that needs it.
$marker = 'rem agent-skills shim (generated by install.ps1)'
$body = @"
@echo off
$marker
if not defined AGENT_SKILLS_HOME goto :missing
node "%AGENT_SKILLS_HOME%\bin\agent-skills" %*
exit /b %ERRORLEVEL%
:missing
echo agent-skills: AGENT_SKILLS_HOME is not set - re-run install.ps1, then open a new terminal 1>&2
exit /b 1
"@ -replace "`r?`n", "`r`n"
$body += "`r`n"

# Pure ASCII by construction, so the encoding cannot matter. Written as ASCII
# rather than UTF-8 so a BOM never reaches cmd.exe, which would echo it.
$enc = New-Object System.Text.ASCIIEncoding

function Install-Shim([string]$name) {
    $dest = Join-Path $binDir "$name.cmd"
    if (Test-Path $dest) {
        $existing = [System.IO.File]::ReadAllText($dest, $enc)
        if ($existing -eq $body) {
            Write-Host "  ok    $dest"
            return
        }
        if ($existing -notmatch [regex]::Escape($marker)) {
            Write-Host "  skip  $dest already exists (not created by this script) - remove it and re-run"
            return
        }
        [System.IO.File]::WriteAllText($dest, $body, $enc)
        Write-Host "  update $dest"
        return
    }
    [System.IO.File]::WriteAllText($dest, $body, $enc)
    Write-Host "  write $dest"
}

Write-Host "install: writing shims into $binDir"
Install-Shim 'agent-skills'
Install-Shim 'skill'

$current = [Environment]::GetEnvironmentVariable('AGENT_SKILLS_HOME', 'User')
if ($current -eq $repo) {
    Write-Host "  ok    AGENT_SKILLS_HOME=$repo"
} else {
    [Environment]::SetEnvironmentVariable('AGENT_SKILLS_HOME', $repo, 'User')
    $env:AGENT_SKILLS_HOME = $repo
    Write-Host "  set   AGENT_SKILLS_HOME=$repo"
    if ($current) { Write-Host "        (was $current)" }
}

$onPath = ($env:Path -split ';') -contains $binDir
if (-not $onPath) {
    Write-Host ""
    Write-Host "note: $binDir is not on PATH. Add it for your user:"
    Write-Host "  [Environment]::SetEnvironmentVariable('Path', [Environment]::GetEnvironmentVariable('Path','User') + ';$binDir', 'User')"
    Write-Host "  (then open a new terminal)"
}

Write-Host ""
Write-Host "Done. Try: agent-skills doctor  (or: skill doctor)"
Write-Host "Note: link/sync/distribute still need Developer Mode or an elevated shell - see #32."
